package com.tavall.hytale.resourcegame.middleware.guild;

public enum GuildPermission {
    INVITE_PLAYER,
    REMOVE_MEMBER,
    PROMOTE_MEMBER,
    DEMOTE_MEMBER,
    MANAGE_TIER_POLICY,
    MANAGE_JOB_TITLE,
    EDIT_GUILD_LOGO,
    MANAGE_TAX_POLICY,
    VIEW_TREASURY,
    SPEND_TREASURY,
    MANAGE_BUILDINGS,
    MANAGE_TROOPS,
    DECLARE_WAR,
    ACCEPT_ALLIANCE,
    START_SIEGE,
    CLAIM_TERRITORY,
    MANAGE_BUFFS,
    CREATE_PETITION,
    FUND_PROPAGANDA,
    MODERATE_GUILD_MESSAGES,
    TRANSFER_LEADERSHIP
}
