<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.tavall</groupId>
        <artifactId>minecraft-main</artifactId>
        <version>0.1.1-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <groupId>com.tavall</groupId>
    <artifactId>minecraft-framework</artifactId>
    <packaging>pom</packaging>

    <name>Tavall Minecraft Framework Parent</name>
    <description>Parent aggregator for Tavall Minecraft framework modules.</description>

    <modules>
        <module>minecraft-framework-game</module>
        <module>kingdom-game-api</module>
        <module>minecraft-backend-api</module>
    </modules>
</project>
