CREATE TABLE IF NOT EXISTS ranks (
    "RANK" VARCHAR(64) NOT NULL,
    "POWERLEVEL" INTEGER NOT NULL DEFAULT 0,
    "PERMISSIONS" JSONB NOT NULL DEFAULT '[]'::jsonb,
    "CREATED_AT" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "UPDATED_AT" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY ("RANK")
);

CREATE TABLE IF NOT EXISTS player_profile (
    "UUID" VARCHAR(36) NOT NULL,
    "NAME" VARCHAR(16) NOT NULL,
    "RANK" VARCHAR(64) NOT NULL DEFAULT 'Member',
    "GRADE" VARCHAR(64) NULL,
    "POWERLEVEL" INTEGER NOT NULL DEFAULT 100,
    "CURRENCY" NUMERIC(12,2) NOT NULL DEFAULT 0.00,
    "GLOBALRANK" NUMERIC(12,2) NOT NULL DEFAULT 0.00,
    "PERMISSIONS" JSONB NOT NULL DEFAULT '[]'::jsonb,
    "METADATA_JSON" JSONB NOT NULL DEFAULT '{}'::jsonb,
    "IP" VARCHAR(64) NOT NULL DEFAULT '',
    "DEBUGGER" SMALLINT NOT NULL DEFAULT 0,
    "CREATED_AT" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "UPDATED_AT" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY ("UUID"),
    UNIQUE ("NAME")
);

INSERT INTO ranks ("RANK", "POWERLEVEL", "PERMISSIONS", "CREATED_AT", "UPDATED_AT")
VALUES
    ('Member', 100, '[]'::jsonb, NOW(), NOW()),
    ('VIP+', 250, '[]'::jsonb, NOW(), NOW()),
    ('God', 1000, '[]'::jsonb, NOW(), NOW())
ON CONFLICT ("RANK") DO UPDATE SET
    "POWERLEVEL" = EXCLUDED."POWERLEVEL",
    "PERMISSIONS" = EXCLUDED."PERMISSIONS",
    "UPDATED_AT" = EXCLUDED."UPDATED_AT";
