package com.tavall.resourcegame.middleware.projection;

public enum ProjectionObjectType {
    GUILD,
    CASTLE,
    RESOURCE_NODE,
    PETITION,
    PROPAGANDA_CAMPAIGN,
    TROOP,
    TRADE_ROUTE,
    PLAYER,
    KINGDOM,
    KINGDOM_BORDER,
    PLAYER_KINGDOM_LOCATION,
    PLAYER_KINGDOM_TRANSITION,
    PLATFORM_INSTANCE,
    INSTANCE_SWITCH_REQUEST,
    EDITABLE_PARAMETER,
    COORDINATE_CONVERSION_DEBUG,
    KINGDOM_SCALING_EVALUATION,
    KINGDOM_CLOCK,
    KINGDOM_SCHEDULE,
    CITIZEN_POPULATION,
    CITIZEN_DISPLAY_ANCHOR,
    UI_SUMMARY
}
