package org.tavall.hytale.resourcegame.runtime;

public enum HytaleAssetId {
  CASTLE_STONE_TIER_ONE,
  UI_CASTLE_PANEL,
  UI_CITIZEN_TROOP_PANEL,
  INTERIOR_MARKER_BANNER,
  DISPLAY_CITIZEN_ANCHOR,
  DISPLAY_TROOP_ANCHOR,
  PLACEHOLDER_FUTURE_SLOT
}
