package org.tavall.control.common;

public enum HighRiskAction {
    PLATFORM_RELINK,
    GUILD_LEADERSHIP_TRANSFER,
    LARGE_TREASURY_SPEND,
    ACCOUNT_DISABLE,
    TWO_FACTOR_DISABLE,
    AUTH_IDENTITY_CHANGE,
    TAX_POLICY_ESCALATION,
    GUILD_DISBAND
}
