package com.tavall.hytale.resourcegame.middleware.cloud;

public enum CloudCommandType {
    INSTALL_WORKLOAD,
    START_WORKLOAD,
    STOP_WORKLOAD,
    RESTART_WORKLOAD,
    DELETE_WORKLOAD,
    OPEN_PORT,
    CLOSE_PORT,
    APPLY_FIREWALL_RULES,
    APPLY_PROXY_CONFIG,
    RUN_HEALTH_CHECK,
    COLLECT_LOGS,
    RUN_BACKUP,
    RESTORE_BACKUP,
    UPDATE_AGENT,
    DRAIN_NODE,
    CANCEL_COMMAND
}
