package org.tavall.control.events.core;

public enum GameEventType {
    CASTLE_CREATED,
    CASTLE_SELECTED,
    CASTLE_INTERACTION_OPENED,
    CASTLE_INTERIOR_ENTER_REQUESTED,
    CASTLE_INTERIOR_ENTERED,
    CASTLE_MOVED,
    CASTLE_VISUAL_UPDATED,

    CITIZEN_CREATED,
    CITIZEN_AGED,
    CITIZEN_JOB_ASSIGNED,
    CITIZEN_PROMOTED_TO_TROOP,
    TROOP_DEMOTED_TO_CITIZEN,
    CITIZEN_MORALE_CHANGED,
    CITIZEN_DIED,

    RESOURCE_ADDED,
    RESOURCE_REMOVED,
    RESOURCE_SET,
    RESOURCE_THRESHOLD_REACHED,
    RESOURCE_SHORTAGE,

    COMPANION_CREATED,
    COMPANION_SUMMONED,
    COMPANION_RECALLED,
    COMPANION_TRAINING_STARTED,
    COMPANION_TRAINING_COMPLETED,
    COMPANION_SKILL_UNLOCKED,
    COMPANION_SKILL_UPGRADED,
    COMPANION_BEHAVIOR_CHANGED,

    KINGDOM_CLOCK_TICK,
    KINGDOM_CLOCK_PHASE_CHANGED,
    KINGDOM_DAY_STARTED,
    KINGDOM_NIGHT_STARTED,
    SCHEDULE_WINDOW_STARTED,
    SCHEDULE_WINDOW_ENDED,

    GAME_RULE_CHANGED,
    FEATURE_FLAG_CHANGED,
    SYSTEM_TOGGLE_CHANGED,
    ITEM_VAULTED,
    ITEM_UNVAULTED,
    LIVE_CONFIG_RELOADED,
    GLOBAL_GUI_UPDATED,

    NODE_REGISTERED,
    NODE_HEARTBEAT,
    NODE_STATUS_CHANGED,
    REMOTE_COMMAND_EXECUTED,
    DISTRIBUTED_EVENT_FORWARDED,
    REMOTE_SMOKE_TEST_COMPLETED
}
