package com.tavall.hytale.resourcegame.ui;

/**
 * Identifiers for UI pages.
 */
public enum UiPageType {
    CASTLE_MAIN,
    CASTLE_INFO,
    CASTLE_CITIZENS,
    CASTLE_TROOPS,
    CASTLE_RESOURCES,
    CASTLE_UPGRADES,
    CASTLE_BUILDINGS,
    FARMSTEAD_MENU,
    RESOURCE_NODE_DETAIL,
    BUILDING_DETAIL,
    INTERIOR_MAIN,
    DEBUG_NAVIGATOR,
    DEBUG_PLACEMENT,
    DEBUG_INTERIOR,
    DEBUG_BUILDINGS,
    DEBUG_WORLD
}
