package com.tavall.hytale.resourcegame.middleware.control;

public enum ControlCommandType {
    CREATE_GUILD,
    CREATE_CASTLE,
    CREATE_RESOURCE_NODE,
    ASSIGN_TROOP_WOUND,
    START_TROOP_HEALING,
    GIVE_RESOURCE,
    REGISTER_GLOBAL_ASSET,
    REGISTER_PLATFORM_ASSET_VERSION,
    BROADCAST_PLATFORM_MESSAGE,
    REFRESH_FRONTEND_PROJECTIONS,
    SYNC_PLATFORM_STATE,
    DEBUG_PLAYER_STATE,
    DEBUG_GUILD_STATE,
    DEBUG_CASTLE_STATE,
    DEBUG_TROOP_HEALING_STATE,
    VERIFY_FRONTEND_ACTION,
    RUN_RESOURCE_TICK,
    RUN_HEALING_TICK,
    RUN_GLOBAL_TICK
}
