package com.tavall.hytale.resourcegame.middleware.control;

public enum ControlPermission {
    VIEW_CONTROL_PANEL,
    EXECUTE_DEBUG_COMMAND,
    EXECUTE_GAMEPLAY_COMMAND,
    EXECUTE_GLOBAL_TICK,
    MANAGE_GLOBAL_ASSETS,
    MANAGE_PLATFORM_ASSETS,
    MANAGE_GUILD_STATE,
    MANAGE_PLAYER_STATE,
    MANAGE_TROOP_STATE,
    MANAGE_HEALING_STATE,
    BROADCAST_GLOBAL_MESSAGE,
    VIEW_AUDIT_LOG,
    MANAGE_CONTROL_OPERATORS
}
