package org.tavall.minecraft.framework.game.ui;

public enum UiScreenKey {
    CASTLE_MAIN,
    CASTLE_INFO,
    CASTLE_CITIZENS,
    CASTLE_TROOPS,
    CASTLE_RESOURCES,
    CASTLE_UPGRADES,
    CASTLE_BUILDINGS,
    FARMSTEAD_MENU,
    NPC_MAIN,
    RESOURCE_NODE_DETAIL,
    BUILDING_DETAIL,
    INTERIOR_MAIN,
    DEBUG_NAVIGATOR,
    DEBUG_PLACEMENT,
    DEBUG_INTERIOR,
    DEBUG_BUILDINGS,
    DEBUG_WORLD
}
